src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AccountRepository::class)
 */
class Account
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $account_type;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $account_number;

    /**
     * @ORM\Column(type="date")
     */
    private $opening_date;

    /**
     * @ORM\Column(type="float")
     */
    private $account_amount;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="user")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Operation::class, mappedBy="account")
     */
    private $account;

    public function __construct()
    {
        $this->account = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccountType(): ?string
    {
        return $this->account_type;
    }

    public function setAccountType(string $account_type): self
    {
        $this->account_type = $account_type;

        return $this;
    }

    public function getAccountNumber(): ?string
    {
        return $this->account_number;
    }

    public function setAccountNumber(string $account_number): self
    {
        $this->account_number = $account_number;

        return $this;
    }

    public function getOpeningDate(): ?\DateTimeInterface
    {
        return $this->opening_date;
    }

    public function setOpeningDate(\DateTimeInterface $opening_date): self
    {
        $this->opening_date = $opening_date;

        return $this;
    }

    public function getAccountAmount(): ?float
    {
        return $this->account_amount;
    }

    public function setAccountAmount(float $account_amount): self
    {
        $this->account_amount = $account_amount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Operation[]
     */
    public function getAccount(): Collection
    {
        return $this->account;
    }

    public function addAccount(Operation $account): self
    {
        if (!$this->account->contains($account)) {
            $this->account[] = $account;
            $account->setAccount($this);
        }

        return $this;
    }

    public function removeAccount(Operation $account): self
    {
        if ($this->account->removeElement($account)) {
            // set the owning side to null (unless already changed)
            if ($account->getAccount() === $this) {
                $account->setAccount(null);
            }
        }

        return $this;
    }
}

src/Controller/SymfobankController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\User;
use App\Entity\Account;
use App\Entity\Operation;

class SymfobankController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        return $this->render('symfobank/index.html.twig', [
        ]);
    }

    /**
     * @Route("/accounts", name="accounts")
     */
    public function accounts(): Response
    {
        $accountRepository = $this->getDoctrine()->getRepository(Account::class);
        $accounts = $accountRepository->findAll();
        return $this->render('symfobank/accounts.html.twig', [
            'accounts' => $accounts,
        ]);
    }
}

templates/symfobank/accounts.html.twig
{% extends 'template.html.twig' %}

{% block title %}Vos comptes{% endblock %}

{% block main %}
    <div class="container">
        <h2 class="my-5 text-center">Vos comptes</h2>
        <div class="row">
            {% for account in accounts %}

                <div class="col-12 col-sm-10 col-md-5">
                    <div class="card text-center">
                        <section class="card-body">
                            <div class="mb-5">
                                <h5 class="card-title">Type de compte : {{account.accountType}}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Numéro de compte : {{account.accountNumber}}</h6>
                            </div>
                            {# <ul class="list-group list-group-flush">
                                <li class="list-group-item">Nom & Prénom</li>
                            </ul> #}
                            <a href="#" class="btn btn-dark">Dépot/Retrait</a>
                            <a href="#" class="btn btn-dark">Virement</a>
                            <a href="#" class="btn btn-dark">Cloturer</a>
                            <hr>
                            <a href="singleAccount" class="text-danger">Voir le compte</a>
                        </section>
                    </div> 
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/symfobank/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}SymfoBank{% endblock %}

{% block main %}
    <div class="container">

        <div class="row m-5 d-flex justify-content-between">
            <div class="card col-md-5 p-0">
                <div class="card-body bg-dark text-white m-0">
                    <h5 class="card-title text-center">Vous connecter</h5>
                </div>
                <div>
                    <p class="card-text p-3">Si vous possédez déjà un compte chez nous, cliquez ici. Vous aurez accès à vos comptes et à la gestion de ceux-ci.</p>
                </div>
                <div class="card-body text-center">
                    <a href="#" class="card-link text-danger">Connexion</a>
                </div>
            </div>

            <div class="card col-md-5 p-0">
                <div class="card-body bg-dark text-white m-0">
                    <h5 class="card-title text-center">S'inscrire</h5>
                </div>
                <div>
                    <p class="card-text p-3">Vous n'avez pas encore de compte dans notre banque, cliquez ici et découvrez toutes les options qui s'offrent à vous.</p>
                </div>
                <div class="card-body text-center">
                    <a href="#" class="card-link text-danger">Inscription</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}